### ISSUE TITLE
Using `middleware.js` sometimes runs Cloudflare email obfuscation JS

### ISSUE THREAD

**Issue by brycewray** [vercel/edge-runtime#286]
## Bug Report

**Current behavior**

My Vercel project — https://static-site-omega.vercel.app/ — has a `middleware.js` file. For some reason, when that file is in use, some pages run the Cloudflare email obfuscation script, `email-decode.min.js`, even though there’s nothing in my code or site config that should invoke this. As of this report, the pages that run the script are:

https://static-site-omega.vercel.app/posts/2020/06/o-say-can-you-ci-cd/
https://static-site-omega.vercel.app/posts/2020/09/mixed-nuts-2020-09/
https://static-site-omega.vercel.app/posts/2020/09/ignition-sequence-start/
https://static-site-omega.vercel.app/posts/2020/10/forward-paas/
https://static-site-omega.vercel.app/posts/2021/09/reply-to-links-feeds/
https://static-site-omega.vercel.app/posts/2021/10/gems-in-rough-10/
https://static-site-omega.vercel.app/posts/2022/03/using-dart-sass-hugo-sequel/
https://static-site-omega.vercel.app/posts/2022/05/using-dart-sass-hugo-github-actions-edition/
https://static-site-omega.vercel.app/posts/2022/06/get-good-git-info-hugo/
https://static-site-omega.vercel.app/posts/2022/06/static-mastodon-toots-hugo/
https://static-site-omega.vercel.app/posts/2022/08/static-embeds-eleventy/
https://static-site-omega.vercel.app/posts/2022/08/static-mastodon-toots-astro/
~~https://static-site-omega.vercel.app/posts/2023/01/another-move-mastodon/~~
https://static-site-omega.vercel.app/posts/2023/02/still-another-move-mastodon/
~~https://static-site-omega.vercel.app/posts/2023/03/headers-up-vercel-edition/~~
https://static-site-omega.vercel.app/posts/2023/03/reluctant-return-twitter/

**Edit**: As of 2023-03-23, the stricken-through items no longer have the problem (perhaps due to edits in the pages since then); however, I've added a later-posted page which does have it.

Here is a sample of browser source code showing where it appears in each of these. Note that it appears prior to my own script for email obfuscation. My script is the same on each of the nearly 300 posts on the site, but my testing showed that only the pages listed above are injecting the Cloudflare code prior to my script.

```html
<div class="contactBtn" data-pagefind-ignore>
  <script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
  <script nonce="NGQ4ZGFmZTBjNQ/OTUyY2IxNzNiZTgxYjI=">
    // The nonce is dynamically generated by the middleware file.
    var email64Link="aHJlZj0ibWFpbHRvOmJ3QGJyeWNld3JheS5jb20=";document.write("<a "+atob(email64Link)+'?subject=“Still another move on Mastodon”">')
  </script>
```

**Expected behavior/code**

The `email-decode.min.js` file would not be part of the page load.

**Possible solution**

Unknown, although I assume it’s somehow related to the fact that Edge Functions and Edge Middleware use Cloudflare Workers.

**Additional context/screenshots**

- When I don’t use `middleware.js`, the Cloudflare script doesn’t appear.
- The script appears on both the custom-domain version (when I assign one) and the `vercel.app` version of each listed page.
- I am guessing from the content of the listed pages that this is somehow being triggered by the presence of the `@` character within the body copy of each page, although in most cases it’s not even related to email (*e.g.*, it can be in a code block from a GitHub Action wherein there’s a line like `uses: actions/checkout@v3`, or in a reference to a Mastodon handle such as `@johndoe@mastodon.social`). This seems to be the only thing they each have in common. What’s even odder is that there are other files with `@` in the body copy which **don’t** exhibit this behavior, so the triggering mechanism — if that’s it — doesn’t “work” consistently. Also, notice what happens if you turn off JavaScript on https://static-site-omega.vercel.app/posts/2023/03/reluctant-return-twitter/ — a Mastodon handle is rendered with an `[email protected]` warning.
- According to the headers, the origin of the script is:
```bash
https://static-site-omega.vercel.app/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js
```
. . . even though there is no `cdn-cgi` subdirectory in my actual output (*e.g.*, https://vercel.com/brycewray/static-site/4zMoAHehYKPdGweAH8H36Ks7HAt6/source).
- The repo from which I deploy, via a GitHub Action, is https://github.com/brycewray/hugo-site.
- The `middleware.js` file is at https://github.com/brycewray/hugo-site/blob/main/.deprecated/middleware.js (keeping it in `.deprecated` until this is resolved, at which time I’ll restore it to the top level).
- The GitHub Action I use appears at the end of this comment.
- I did try deploying straight from the Git repo without a GitHub Action — *i.e.*, using the normal deploy method — but still encountered the same oddity concerning the Cloudflare script.
- I even tried using a `replace` statement in the `middleware.js` file to eliminate the script from appearing in the HTML, but this only made the `[email protected]` warning show up as if the script were still there but being blocked. This further suggests it’s somehow being injected during the deployment.
- *[No screenshots]*

Here is the GitHub Action (not currently in https://github.com/brycewray/hugo-site/tree/main/.github/workflows while this issue remains unresolved):

```yaml
name: Deploy to Vercel

# To do a push without triggering this GHA, include one of
# the following in the **commit message**
# (INCLUDING the brackets AND case-sensitivity):
#
# [skip ci]
# [ci skip]
# [no ci]
# [skip actions]
# [actions skip]
#
# “Alternatively, you can end the commit message
# with two empty lines followed by either
# `skip-checks: true` or `skip-checks:true`.”
#
#
# ref: https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs

on:
  push:
    branches:
      - main

env:
  HUGO_VERSION: 0.111.3 # will get Extended Version below
  DART_SASS_VERSION: 1.59.3
  PAGEFIND_VERSION: 0.12.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Fetch **all** history (not just deploy commit) for Hugo's .GitInfo and .Lastmod
          # See https://discourse.gohugo.io/t/problems-with-gitinfo-in-ci/22480
      - name: Download Hugo
        run: wget https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_extended_${{ env.HUGO_VERSION }}_linux-amd64.deb -O hugo_extended_${{ env.HUGO_VERSION }}_linux-amd64.deb
        # 0.103.0 began new naming convention
      - name: Install Hugo
        run: sudo dpkg -i hugo*.deb
      - name: Download Embedded Dart Sass
        run: curl -LJO https://github.com/sass/dart-sass-embedded/releases/download/${{ env.DART_SASS_VERSION }}/sass_embedded-${{ env.DART_SASS_VERSION }}-linux-x64.tar.gz
      - name: Unpack Embedded Dart Sass
        run: |
          tar -xvf sass_embedded-${{ env.DART_SASS_VERSION }}-linux-x64.tar.gz
          sass_embedded/dart-sass-embedded --version
      - name: Add Embedded Dart Sass to the PATH
        run: echo "$GITHUB_WORKSPACE/sass_embedded" >> $GITHUB_PATH
      - name: Install Pagefind
        uses: supplypike/setup-bin@v3
        with:
          uri: "https://github.com/CloudCannon/pagefind/releases/download/v${{ env.PAGEFIND_VERSION }}/pagefind_extended-v${{ env.PAGEFIND_VERSION }}-x86_64-unknown-linux-musl.tar.gz"
          name: "pagefind_extended"
          version: ${{env.PAGEFIND_VERSION}}
      - name: Build site with Hugo
        run: hugo --verbose --minify
      - name: Move "excerpts" feeds (RSS/Atom and JSON)
        run: |
          mv public/posts/index.xml public/index-excerpts.xml
          mv public/posts/index.json public/index-excerpts.json
      - name: Move Vercel-specific files to `/public`
        run: |
          mv middleware.js public/middleware.js
          mv vercel.json public/vercel.json
      - name: Run Pagefind
        run: pagefind_extended --source "public"
      - name: Publish to Vercel (Betahuhn)
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN_STATIC_SITE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID}}
          WORKING_DIRECTORY: 'public'
      # - name: Publish to Vercel (amondnet)
      #   uses: amondnet/vercel-action@v20 #deploy
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN_STATIC_SITE }}
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     # vercel-args: '--prod' # optional
      #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
      #     vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
      #     working-directory: 'public'
      - name: Remove Vercel-specific files from build
        run: |
          rm -rf public/middleware.js
          rm -rf public/vercel.json
```
